export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const NEW_MESSAGE = 'NEW_MESSAGE';